# Basic Information 
title: Xiaotian Ye
position: Undergraduate Student
affiliation: BUPT SCS
# affiliation_link: https://www.bupt.edu.cn/
# affiliation_logo: /assets/img/profile.png
email: yexiaotian[AT]bupt.edu.cn

url: https://xiaotianye.me # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl: "Acruxos.github.io"

# Search Engine Optimization (SEO)
keywords: xiaotian ye, ye xiaotian, xiaotianye, yexiaotian, 叶笑天
canonical: https://xiaotianye.me
description: Xiaotian Ye is an undergraduate student at Beijing University of Post and Telecommunications. His research lies in machine learning, large language models, and knowledge representation.

# The option is used to enable the Illinois template.
# enable_hopkins_logo: true

# The option is used to show the last update time.
enable_last_update: true

# Links
link_type: icon #text/icon
google_scholar: https://scholar.google.com/citations?user=F0tij1oAAAAJ
github_link: https://github.com/Acruxos/
linkedin: https://www.linkedin.com/in/xiaotian-ye/
cv_link: /files/cv.pdf
semantic_scholar: https://www.semanticscholar.org/author/Xiaotian-Ye/2286432237
# twitter: https://twitter.com/YaoyaoLiu1/

# Images 
avatar: /assets/img/profile.png
favicon: /assets/img/favicon.png
favicon_dark: /assets/img/favicon-dark.png

# Footnotes
footnote: Powered by Jekyll and Minimal Light theme.
footnote_link: https://github.com/yaoyao-liu/minimal-light

# Analytics
# Please remove the following lines about analytics services if you fork my project. 
# Otherwise, the analytics information of your website will be recorded to my ClustrMaps accounts.
clustrmaps_id: IAGgowD5DDH0zd6UpcCd6uQu_3zP8YlAiYJmVKJQ7OA

# The following files will be removed from the generated website.
exclude:
  - build.sh
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CNAME
